### ISSUE TITLE
编译不过

### ISSUE THREAD

**Issue by xuecat** [mutouyun/cpp-rgb2yuv#1]
亲！何必用vs2015；每个c++版本都会更改点模板语法，我vs2012编译pixel_walker.hxx各种报错。

**Comment by mutouyun** [comment]
咦。。我只加了一点儿C++11的东西就编译不过么。。记得vs2012对C++11也是有一定支持的，麻烦把报错发给我看看？
毕竟这两年都用的是最新的vs，2012已经好久不用了，这个库之前没有使用C++11特征，更新了之后就没再考虑老版本C++了。

**Comment by xuecat** [comment]
题主都回复我了，那我也必须响应：
1>------ 已启动生成: 项目: test, 配置: Debug Win32 ------
1>项目文件包含 ToolsVersion="14.0" 设置，但此工具集未知或缺失。您可以通过为此工具集安装相应的 .NET Framework 来解决此问题。将项目视为具有 ToolsVersion="4.0" 设置。
1>  test.cpp
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\scope_block.hxx(52): error C2253: “scope_block<T,AllocT>”: 纯说明符或抽象重写说明符只允许在虚函数上使用
1>          c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\scope_block.hxx(127): 参见对正在编译的类 模板 实例化“r2y::scope_block<T,AllocT>”的引用
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(13): error C2039: “enable_if_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(13): error C2143: 语法错误 : 缺少“;”(在“<”的前面)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(13): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(13): error C2988: 不可识别的模板声明/定义
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(13): error C2059: 语法错误:“<”
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(13): error C2653: “F”: 不是类或命名空间名称
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(25): error C2039: “remove_reference_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(26): error C2039: “enable_if_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(26): error C2653: “F”: 不是类或命名空间名称
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(28): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(28): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(39): error C2039: “enable_if_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(39): error C2143: 语法错误 : 缺少“;”(在“<”的前面)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(39): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(39): error C2086: “int r2y::enable_if_t”: 重定义
1>          c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(13) : 参见“r2y::enable_if_t”的声明
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(39): error C2988: 不可识别的模板声明/定义
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(39): error C2059: 语法错误:“<”
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(39): error C2653: “F”: 不是类或命名空间名称
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(66): error C2039: “remove_reference_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(67): error C2039: “enable_if_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(67): error C2653: “F”: 不是类或命名空间名称
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(69): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(69): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(84): error C2039: “enable_if_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(84): error C2143: 语法错误 : 缺少“;”(在“<”的前面)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(84): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(84): error C2086: “int r2y::enable_if_t”: 重定义
1>          c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(13) : 参见“r2y::enable_if_t”的声明
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(84): error C2988: 不可识别的模板声明/定义
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(84): error C2059: 语法错误:“<”
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(84): error C2653: “F”: 不是类或命名空间名称
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(104): error C2039: “remove_reference_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(105): error C2039: “enable_if_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(105): error C2653: “F”: 不是类或命名空间名称
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(107): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(107): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(136): error C2039: “enable_if_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(136): error C2143: 语法错误 : 缺少“;”(在“<”的前面)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(136): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(136): error C2086: “int r2y::enable_if_t”: 重定义
1>          c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(13) : 参见“r2y::enable_if_t”的声明
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(136): error C2988: 不可识别的模板声明/定义
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(136): error C2059: 语法错误:“<”
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(136): error C2653: “F”: 不是类或命名空间名称
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(152): error C2039: “remove_reference_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(153): error C2039: “enable_if_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(153): error C2653: “F”: 不是类或命名空间名称
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(155): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(155): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(174): error C2039: “enable_if_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(174): error C2143: 语法错误 : 缺少“;”(在“<”的前面)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(174): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(174): error C2086: “int r2y::enable_if_t”: 重定义
1>          c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(13) : 参见“r2y::enable_if_t”的声明
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(174): error C2988: 不可识别的模板声明/定义
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(174): error C2059: 语法错误:“<”
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(174): error C2653: “F”: 不是类或命名空间名称
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(204): error C2039: “remove_reference_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(205): error C2039: “enable_if_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(205): error C2653: “F”: 不是类或命名空间名称
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(207): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(207): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(225): error C2039: “enable_if_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(225): error C2143: 语法错误 : 缺少“;”(在“<”的前面)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(225): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(225): error C2086: “int r2y::enable_if_t”: 重定义
1>          c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(13) : 参见“r2y::enable_if_t”的声明
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(225): error C2988: 不可识别的模板声明/定义
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(225): error C2059: 语法错误:“<”
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(225): error C2653: “F”: 不是类或命名空间名称
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(252): error C2039: “remove_reference_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(253): error C2039: “enable_if_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(253): error C2653: “F”: 不是类或命名空间名称
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(255): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(255): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(291): error C2039: “enable_if_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(291): error C2143: 语法错误 : 缺少“;”(在“<”的前面)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(291): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(291): error C2086: “int r2y::enable_if_t”: 重定义
1>          c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(13) : 参见“r2y::enable_if_t”的声明
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(291): error C2988: 不可识别的模板声明/定义
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(291): error C2059: 语法错误:“<”
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(291): error C2653: “F”: 不是类或命名空间名称
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(303): error C2039: “remove_reference_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(304): error C2039: “enable_if_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(304): error C2653: “F”: 不是类或命名空间名称
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(306): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(306): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(322): error C2039: “enable_if_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(322): error C2143: 语法错误 : 缺少“;”(在“<”的前面)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(322): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(322): error C2086: “int r2y::enable_if_t”: 重定义
1>          c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(13) : 参见“r2y::enable_if_t”的声明
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(322): error C2988: 不可识别的模板声明/定义
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(322): error C2059: 语法错误:“<”
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_walker.hxx(322): error C2653: “F”: 不是类或命名空间名称
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_iterator.hxx(10): error C2143: 语法错误 : 缺少“;”(在“{”的前面)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_iterator.hxx(10): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_iterator.hxx(417): error C3083: “detail_iterator_”:“::”左侧的符号必须是一种类型
1>          c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_iterator.hxx(423): 参见对正在编译的类 模板 实例化“r2y::iterator<S>”的引用
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_iterator.hxx(417): error C2143: 语法错误 : 缺少“,”(在“<”的前面)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_iterator.hxx(419): error C3083: “detail_iterator_”:“::”左侧的符号必须是一种类型
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_iterator.hxx(419): error C2143: 语法错误 : 缺少“;”(在“<”的前面)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_iterator.hxx(419): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_iterator.hxx(419): error C2238: 意外的标记位于“;”之前
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_iterator.hxx(422): error C2653: “base_t”: 不是类或命名空间名称
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_iterator.hxx(422): error C2873: “base_t”: 符号不能用在 using 声明中
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_convertor.hxx(24): error C2062: 意外的类型“auto”
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_convertor.hxx(24): error C3553: decltype 应为表达式而不是类型
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_convertor.hxx(24): error C2059: 语法错误:“)”
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_convertor.hxx(25): error C2334: “{”的前面有意外标记；跳过明显的函数体
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_convertor.hxx(45): error C2039: “enable_if_t”: 不是“std”的成员
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_convertor.hxx(45): error C2143: 语法错误 : 缺少“;”(在“<”的前面)
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_convertor.hxx(45): error C2433: “r2y::convertor::enable_if_t”: 不允许在数据声明中使用“__forceinline”
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_convertor.hxx(45): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_convertor.hxx(45): error C2238: 意外的标记位于“;”之前
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_convertor.hxx(45): error C2988: 不可识别的模板声明/定义
1>c:\users\xuecat\desktop\cpp-rgb2yuv\include\detail\pixel_convertor.hxx(45): fatal error C1003: 错误计数超过 100；正在停止编译
========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

我想：其实和c++11无关，和编译器有关，编译器语法而已！！！

**Comment by mutouyun** [comment]
vs2012貌似还不支持这个：scope_block(scope_block const &) = delete;
也不支持enable_if_t、remove_reference_t等。
粗略的看了下，主要问题应该就这两个地方，把scope_block的拷贝构造弄成private的，然后把enable_if_t换成对应的enable_if之类的type traits应该就可以了。

你试试？

**Comment by xuecat** [comment]
饿！！！虽然还是不行。但是我已经用其它方式来解决问题了！！唯一佩服的就是楼主的模板能力叼叼叼。。。。。。。再次被激励！！！！！！

**Comment by mutouyun** [comment]
谢谢！^_^

最开始的老版本，我改进成C++11之前肯定是可以支持的，就是那个版本没有右值引用，所以move语义的实现用的是类似auto_ptr的方法……
